packages:
  - components/*
  - docs
onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/free-brands-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - esbuild
  - svelte-preprocess
