name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test

  deploy:
    name: Deploy Documentation
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter "./components/**" build
      - run: pnpm --filter wc-docs run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build